apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
commonLabels:
  app.kubernetes.io/name: prometheus
resources:
- namespace.yaml
- prometheus-operator.yaml
- serviceaccount.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- prometheus.yaml
- service.yaml
