apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
commonLabels:
  app.kubernetes.io/name: grafana
resources:
- deployment.yaml
- service.yaml
configMapGenerator:
- name: grafana-datasources
  files:
  - config/datasources/prometheus.yaml
- name: grafana-dashboards
  files:
  - config/dashboards/default.yaml
  - config/dashboards/fluent-bit-stats.json
