apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
commonLabels:
  app.kubernetes.io/name: kube-state-metrics
resources:
- cluster-role.yaml
- cluster-role-binding.yaml
- service-account.yaml
- deployment.yaml
- service.yaml
- servicemonitor.yaml
