apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging
bases:
- ../default
secretGenerator:
- name: fluent-bit-credentials
  files:
  - google-service-credentials.json
patchesStrategicMerge:
- ./fluent-bit-cloud-logging.yaml
