{
 "title": "fluent-bit stats",
 "tags": [
  "logging",
  "fluent-bit"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "fluent-bit version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fluentbit_build_info{namespace=\"logging\", service=\"fluent-bit\"}) by (version)",
     "legendFormat": "v{{version}}"
    }
   ]
  },
  {
   "title": "Input bytes total (24h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(fluentbit_input_bytes_total{namespace=\"logging\", service=\"fluent-bit\"}[24h]))"
    }
   ]
  },
  {
   "title": "Output bytes total (24h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(fluentbit_output_proc_bytes_total{namespace=\"logging\", service=\"fluent-bit\"}[24h]))"
    }
   ]
  },
  {
   "title": "Input bytes per sec (5min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_bytes_total{namespace=\"logging\", service=\"fluent-bit\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Output bytes per sec (5min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_bytes_total{namespace=\"logging\", service=\"fluent-bit\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    },
    {}
   ]
  },
  {
   "title": "Input records per sec (5min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_records_total{namespace=\"logging\", service=\"fluent-bit\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Output records per sec (5min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_records_total{namespace=\"logging\", service=\"fluent-bit\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}