apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging
commonLabels:
  app.kubernetes.io/name: fluent-bit
resources:
- namespace.yaml
- serviceaccount.yaml
- configmap.yaml
- daemonset.yaml
- service.yaml
- servicemonitor.yaml
