apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging
commonLabels:
  app.kubernetes.io/name: fluent-bit
resources:
- namespace.yaml
- serviceaccount.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- daemonset.yaml
- service.yaml
- servicemonitor.yaml
configMapGenerator:
- name: fluent-bit-config
  files:
  - config/fluent-bit-input.conf
  - config/fluent-bit-filter.conf
  - config/fluent-bit-output.conf
  - config/fluent-bit-service.conf
  - config/fluent-bit.conf
  - config/parsers.conf
